<?php

return array (
  'exposition-1-title' => 'Conquering Central Asia by tsarist Russia and the struggle of  local people against colonialists.',
  'exposition-1-text' => 'This section is dedicated to the colonial period in the history of Uzbekistan. Thousands of our patriots laid down their heads, fighting for the freedom and independence of our land during the described period of time. Throughout the entire colonial period, which lasted about 150 years, there was a continuous struggle for the freedom of the Fatherland. That is why the disclosure of the historical truth about our ancestors who sacrificed themselves for freedom and perpetuating their memory are the most important guiding aspects of the museum\'s exposition. <br>
     The exhibits in the section include materials related to the history of the conquest of Central Asia by tsarist Russia and the struggle of the local population against colonial oppression.',
  'exposition-2-title' => 'National revival movement, its manifestations and practical directions.',
  'exposition-2-text' => 'As a result of colonial policy in the late XIX - early centuries, the political system, economy and culture of Turkestan were in a state of crisis.
      The advanced intelligentsia of the region founded an enlightenment movement in order to liberate the country from the yoke of Tsarist Russia, awaken the nation, open new ways not only for the economic, but also for the cultural development of the country. <br>
       In Turkestan, this movement was called "Jadidism". The Jadids considered raising the cultural and educational level of the local population as their main objective. <br>
      This section of the exposition contains portraits of the most prominent representatives of the Jadid educational movement. There are photos of new schools created by them, samples of the national periodicals of Turkestan, posters of theatrical performances of amateur theater companies in Kokand and Andijan as well.',
  'exposition-3-title' => 'The liquidation of provisional government of autonomous Turkistan and beginning of the soviet state’s repressions policy (1917–1924)',
  'exposition-3-text' => 'The February Revolution of 1917 in Russia and the overthrow of the emperor led to the dramatic political changes in Turkestan. The royal power in the region was abolished but the newly formed government perceived Turkestan as a Russian colony and established the same political system here as in Russia. The revolutionary mood in Russia had a significant impact on the Jadid educational movement. The first national public organizations such as "Shuroi Islam" and "Ulamo" began to form in Turkestan. <br>
     In October 1917, the Bolsheviks staged a coup d\'etat in Russia. And in Tashkent on the 1st of November the Bolsheviks arrested members of the committee of the Provisional Government of Turkestan and announced the establishment of Soviet power in Turkestan. <br>
      On November 26-28, 1917, the Soviet government issued a decree stating that each people is free to choose its own destiny. The National Progressive Movement of Turkestan in Kokand convenes the IV Extraordinary Congress of Muslims of Turkestan. Various issues were discussed at the congress, including the idea of creating Turkestan Autonomy. By the majority of votes Turkestan was declared an Autonomy. <br>
    The Bolsheviks refused to recognize the Turkestan Autonomy. On February 19, 1918, the Red Army launched an offensive against the government of the Turkestan Autonomy in the city of Kokand. This Section contains documentary evidence of the defeat of the Turkestan Autonomy in Kokand, which lasted only 72 days.',
  'exposition-4-title' => 'Resistance and armed uprisings towards oppression and aggression in central Asia (1918–1924)',
  'exposition-4-text' => 'The violence of the Soviet regime became the cause of sharp discontent and resistance of the people. Armed movements against Soviet power began throughout the country. Especially in the Fergana Valley, the movement became violent and massive. The leaders of the resistance were local leaders Madaminbek, Katta Ergash, Shermukhammadbek. The map shows the centers of armed confrontations that began in February 1918 and lasted until 1924.',
  'exposition-5-title' => 'The policy of the Soviet Government directed to “collectivization” and “kulaks” (rich peasants) dispossession and its tragic consequences (1930–1936).',
  'exposition-5-text' => 'This section is devoted to the repressions of the Soviet government in the economic sphere in the early 20-30s. In the XX century, in the process of implementing the monopoly policy of the Soviet government, violent processes of "collectivization" and "dispossession" began. Thousands of land and water facilities were transferred to the state. <br>
     The materials of the exposition tell about how the Soviet government confiscated housing and property of thousands of people who were not only large landowners but also artisans - shrubs, merchants, landlords, entrepreneurs, dehkans, clergy and all those who used the daily hired force, and sent them into exile with whole families, declaring them to be “kulaks”. <br>
     The map shows the directions to which “kulaks” were sent from Uzbekistan. Also, the section presents models of the wagons in which the "kulaks" were transported; "Dugout tents" in which they were forced to live. <br>
     The video materials contain memories of children whose parents were dispossessed and expelled from the country, about the difficult conditions in which they were forced to live and work.',
  'exposition-6-title' => 'Political repressions at the beginning of the 1930s (1929-1936)',
  'exposition-6-text' => 'By the early 1930s, the system of administrative bureaucracy was firmly entrenched and mobilized all its might in the widespread propaganda of the ideology of Bolshevism. It was at this time that the oppression and persecution of those who opposed the existing ideology of anti-scientific and inhuman reforms carried out by the Soviet government in the socio-economic and cultural spheres intensified. In particular, representatives of the local intelligentsia, who opposed national values to the ideology of Bolshevism, participants in the resistance movement of 1918-1924, and their relatives, were subjected to the repressions. <br>
     Dissenters were sent to camps and involved in construction work at such large facilities as Belomorkanal, Belbatlag and Dmitlag, where the labor of political prisoners was predominantly used. <br>
     The 6th section of the museum exposition covers all of the above processes.',
  'exposition-7-text' => 'The political repressions of the Soviet period under the leadership of V. Stalin in the period 1937-38 are undoubtedly one of the most tragic pages in the history of mankind. At that time, any dissent or action against the Soviet government and its ideology was severely suppressed. These actions were primarily directed against statesmen, party and government cadres. Not only outstanding representatives of the national intelligentsia - scientists, writers, cultural and art workers, but also members of their families fell victim to the repressions of that time. <br>
     The exposition features photographs of the famous statesman Fayzulla Khodjaev. At that time, he was the head of Uzbekistan. He himself was shot, and his whole family and close relatives were sent to prison. <br>
     There are also photographs of the wives of such prominent Uzbek poets and public figures as: Chulpan, Fitrat, Akbar Rustamov, Abdulkhay Tadzhiev who fell under the repressions. <br>
     Photos of students who were sent to study in Germany in 1922, subsequently accused of spying for Germany and shot before the outbreak of the World War II are featured in this section as well.',
  'exposition-7-title' => 'Political repressions in 1937-1938',
  'exposition-8-title' => 'Political repressions in 1940-1950',
  'exposition-8-text' => 'The World War II (1939-1945) is undoubtedly one of the greatest tragedies in human history. On June 22, 1941, Hitler\'s Germany suddenly attacked the USSR. From the first days of the war, the people of Uzbekistan made every possible effort to defeat fascism. Martial law was declared in the country and all resources were directed to ensure the country\'s defense. <br>
     But even in such difficult days, the Soviet government did not abandon its repressive policy. During the World War II, under the pretext of "preventing the manifestation of compassion for fascism," ethnic repressions began against the nationalities living in the border areas. As a result: thousands of Koreans, Crimean Tatars, Poles, Meskhetian Turks, Volga Germans and representatives of other nationalities, whose lands bordered on Japan, Turkey and Poland, were forcibly deported from their places of residence to other republics, in particular to Uzbekistan. Providing them with shelter, work and food had laid a heavy burden on the shoulders of the Uzbek people. <br>
      In the late 1940s and early 1950s, a new wave of repression broke out. The main blow fell again on the ranks of the progressive intelligentsia: representatives of science and art, poets and writers, who in their works touched upon the issues of history, everyday life and traditions, the spiritual heritage of the Uzbek people. <br>
     As a result, they were accused of "idealizing the past", of nationalism, with a sentence of up to 25 years in prison.',
  'exposition-9-title' => 'Repressions of 1980’s: “The Case of Cotton” campaign',
  'exposition-9-text' => 'The transformation of cotton into a monoculture cultivated on the territory of Uzbekistan, as well as the irrational use of natural resources, led to the tragedy of the Aral Sea in the 80s of the XX century. <br>
     At this time, the planned system of economic management forced people to give false numbers in reports at regular party congresses. Theft and registration were a common practice throughout the Soviet Union. <br>
     However, a show trial was needed for all the republics of the former Soviet Union and, as a result, a high-profile campaign called “The Case of Cotton” was organized in Uzbekistan, during which thousands of innocent people were sentenced to long prison terms. <br>
     It also tells about the vigorous activities of the first president of Uzbekistan, Islam Karimov, which began in 1986 in Kashkadarya and aimed at the rehabilitation of innocent victims of the “The Case of Cotton”.',
  'exposition-10-text' => 'After gaining independence, on the basis of historical facts and archival materials, large-scale work was carried out to restore national values and historical justice. <br>
      The historical truth has been restored in relation to such great statesmen and commanders as Amir Temur, Zakhiriddin Muhammad Babur, Mirzo Ulugbek, Jalaliddin Manguberdi. Also, the section tells that over the years of independence, colossal work has been done to restore religions and cultures of values, study the history, foundations, cultural and architectural heritage of Islam, which have been restored and have found their place of honor in the history of Uzbekistan. <br>
      This section reflects the broad opportunities presented to our youth by their high achievements and successes in sports, education, science and technology, culture and art. <br>
      The expositions of the museum contain photographs of our compatriots, a large number of documents and materials related to the political repressions of that time, a map of the GULAGs, personal belongings of victims of repressions, and also a GAZ 11-73 car, reminiscent of the horrors of the repressions of 1930-1938. <br>
     The halls are equipped with 10 touch-sensitive kiosks and 9 monitors that contain rare archival materials, eyewitness memories, interviews, samples of national musical creativity. These allow visitors of the museum to fully immerse themselves in the atmosphere of that time and, at least in part, to feel the heaviness and oppression of the terrible period of repressions.',
  'exposition-10-title' => 'Rehabilitation of historical truth, eternalizing the memory of the repressions’ victims, important historical arrangements directed to restoring and developing national values during the years of Independence after 1991.',
);
