<?php

return array (
  'exposition-1-title' => 'O’rta Osiyo (Turkiston)ning chor Rossiyasi tomonidan bosib olinishi va mahalliy xalqning bunga qarshi kurashi',
  'exposition-1-text' => 'Mazkur bo’lim O’zbekistonning mustamlaka davri tarixiga bag’ishlanadi. Aynan shu davrda mamlakat mustaqilligi, erk va ozodlik uchun kurashlar davomida xalqimizning minglab vatanparvar va fidoyi farzandlari halok bo’ldilar. Qariyb 150 yil davom etgan mustamlaka davri tinimsiz kurashlar davri bo’ldi. Shu sababli istiqlol yo’lida shahid ketgan ajdodlar haqidagi tarixiy haqiqatni aks ettirish, ular xotirasini abadiylashtirish muzey ekspozitsiyasining muhim yo’nalishlaridan biri hisoblanadi. <br>
Bo’lim ekspozitsiyasida joy olgan eksponatlar O’rta Osiyoning Chor Rossiyasi tomonidan istilo etilishi xronologiyasi, mustamlakachilik zulmiga qarshi kurashlar bilan bog’liq materiallardan iborat.',
  'exposition-2-title' => 'Milliy uyg’onish harakati, uning namoyon bo’lishi va amaliy yo’nalishlari',
  'exposition-2-text' => 'Turkiston o’lkasi XIX asr oxiri – XX asr boshlarida mustamlakachilik siyosati oqibatida siyosiy, madaniy, iqtisodiy tanazzulga yuz tutdi. O’lkaning ilg’or ziyolilari Chor Rossiyasi istibdodidan qutulish, millatni uyg’otish, nafaqat iqtisodiy, balki madaniy taraqqiyot sari yo’l ochish, xalqqa ziyo tarqatish maqsadida ma’rifatparvarlik harakatiga asos soldilar. Muzeyning ikkinchi bo’limi ana shu jarayonlarga bag’ishlangan bo’lib, unda jadidlarning iqtisodiy-ijtimoiy va madaniy hayotni yangilash, jamiyatda islohotlar o’tkazishga qaratilgan faoliyatlari o’z aksini topgan. <br>
Ma’rifatparvarlarning millat kelajagi yo’lidagi bu harakatlari mustamlakachi hukumat tomonidan qattiq tazyiqqa uchradi. Ammo ma’rifatparvarlik harakati tazyiq va ta’qiblarga qaramay, keng quloch yoya boshladi va ayrim jabhalarda yashirin tarzda davom etdi. Turkistonda bu harakat jadidchilik deb nom oldi.<br>
Bo’limdagi ekspozitsiyalarda ma’rifatparvarlik harakatining eng faol namoyandalarining suratlari, yangi usul maktablari, o’sha davrda chop etilgan milliy matbuot namunalari aks ettirilgan, Qo’qon, Andijon teatr havaskorlari milliy teatr truppalari sahnalashtirgan teatr  afishalari o’z aksini topgan.',
  'exposition-3-title' => 'Turkiston Muxtoriyat hukumatining tugatilishi va sovet davlati qatag’on siyosatining boshlanishi (1917–1924-yillar)',
  'exposition-3-text' => '1917-yil fevral oyida Rossiyada amalga oshirilgan inqilob natijasida Imperatorning taxtdan ag’darilishi Turkistonda ham keskin siyosiy o’zgarishlarga turtki bo’ldi. O’lkada chor hukmronligiga barham berildi, ammo yangi tashkil topgan Muvaqqat hukumat Turkistonga Rossiya mustamlakasi sifatida qarab, bu yerda ham Rossiyadagi siyosiy o’zgarishlarni to’g’ridan-to’g’ri amalga oshirdi. Rossiyadagi inqilobiy kayfiyat milliy ma’rifatparvarlarga jiddiy ta’sir o’tkazdi. Shu paytdan boshlab ularning siyosiy faoliyati jonlanib, ilk milliy ijtimoiy tashkilotlar tashkil etila boshlandi. “Sho’royi islom”, “Ulamo” singari o’z siyosiy tashkilotlarini tashkil qildilar. <br>
1917-yil oktabirda Rossiyada bolsheviklar tomonidan davlat to’ntarilishi amalga oshirildi, shu kunlarda ular Turkistonda ham hokimiyatni zo’rlik bilan egalladilar. Bolsheviklar tomonidan Toshkentda 1-noyabrda Muvaqqat hukumatning Turkiston qo’mitasi a’zolari qamoqqa olinib, Turkistonda sovet hokimiyati o’rnatilgani e’lon qilindi. <br>
Turkistondagi milliy taraqqiyparvar kuchlar Sovet hukumatining har bir xalq o’z taqdirini belgilashi haqidagi dekretiga binoan 1917-yil 26–28-noyabr kunlarida Qo’qon shahrida Turkiston o’lka musulmonlarining favqulodda IV-qurultoyini chaqirdilar. Qurultoyda muhim masalalar yuzasidan munozaralar bo’lib o’tdi. Ko’pchilik Turkiston Muxtoriyatini e’lon qilish g’oyasini qo’llab-quvvatladi. Demokratik asosda yangi hukumat – Turkiston Muxtoriyati e’lon qilindi. <br>
Ammo bolsheviklar Turkiston Muxtoriyatini tan olishni istamadilar. 1918-yilning 19-fevralida Qo’qon shahrida faoliyat ko’rsatayotgan Turkiston Muxtoriyati hukumatiga qarshi bolsheviklar hukumati qo’shini – qizil armiya hujum boshladi. Bo’lim ekspozitsiyalari mazkur jarayonlarga bag’ishlangan bo’lib, undagi eksponatlarda Qo’qon shahrida Turkiston Muxtoriyatiga qarshi bolsheviklar uyushtirgan qatag’on siyosati va uning fojiali oqibatlari aks ettirilgan.',
  'exposition-4-text' => 'Sovet hokimiyatining zo’ravonligi xalqning keskin qarshiligi va noroziligiga sabab bo’ldi. Butun o’lka bo’ylab sovet hokimiyatiga qarshi qurolli qarshilik harakati boshlanib ketdi. Bu harakat, ayniqsa, Farg’ona vodiysida keskin va ommaviy tus oldi. Qarshilik harakatiga Madaminbek, katta Ergash, Shermuhammadbek kabi mahalliy sardorlar yetakchilik qildilar. <br>
Ekspozitsiyada Turkistonda sovet hokimiyatiga qarshi 1918-yil fevralda boshlanib, 1924-yilgacha davom etgan qurollik qarshilik harakati o’choqlari aks ettirilgan.',
  'exposition-4-title' => 'O’rta Osiyo mintaqasida zulm va bosqinchilikka nisbatan qarshilik harakati va qurolli chiqishlar (1918–1924-yillar)',
  'exposition-5-text' => 'Mazkur bo’lim Sovet hokimiyatining iqtisodiy sohada olib borgan qatag’on siyosatiga bag’ishlanadi. Sovet hokimiyati 20-yillar oxiri – 30-yillar boshida amalga oshirgan yer-suv islohoti, kollektivlashtirish, xususiy mulkni tugatish, sanoat va qishloq xo’jaligida davlat monopoliyasini o’rnatish siyosatini amalga oshirish jarayonida “quloqlashtirish” kampaniyasi o’tkazilib, bolsheviklar minglab xo’jaliklarning yer-suvini davlat ixtiyoriga tortib oldilar. <br>
Ekspozitsiyada qayd etilgan ma’lumotlarning ko’rsatishicha, sovet hokimiyati nafaqat yirik yer egalari, balki xususiy ishlab chiqarish vositasiga ega bo’lgan hunarmandlar, savdogarlar, ijaraga mulk va vosita berganlar, yollanma mehnatdan foydalangan tadbirkorlar, o’rtahol dehqonlar, diniy ulamolar ham uy-joyi, mol-mulkidan mahrum etilib, “quloq” sifatida  oila a’zolari bilan birga o’z yurtidan badarg’a qilindi. <br>
Undan O’zbekistondan chetga va O’rta Osiyoga surgun qilingan “quloq”lar manzillari, surgun yo’nalishlari aks ettirilgan 5 ta xarita, “quloq” qilinganlar surgunga olib ketilgan poyezd vagoni va ular yashagan chayla-yerto’la maketlari o’rin olgan. <br>
Ekspozitsiyaga joylangan videomateriallarda “quloq” qilingan oilalar farzandlarining xotiralari o’rin olgan bo’lib, ular qanday og’ir sharoitlarda yashab, mehnat qilganlari haqida ma’lumot beradi.',
  'exposition-5-title' => 'Sovet hokimiyatining “kollektivlashtirish” va “quloqlashtirish” siyosati, uning fojiali oqibatlari (1930–1936-yillar)',
  'exposition-6-title' => '30-yillarning boshlaridagi siyosiy qatag’onlar (1929–1936-yillar)',
  'exposition-6-text' => '30-yillar boshiga kelib ma’muriy-buyruqbozlik tizimi mustahkam qaror topib, bolsheviklar mafkurasini keng targ’ib qilishga zo’r berila boshlandi. Aynan shu davrda mazkur mafkuraga hamda Sovet hokimiyatining ijtimoiy-iqtisodiy va ma’naviy sohalarda zo’ravonlik bilan olib borgan g’ayrimilliy, g’ayriinsoniy va g’ayriqonuniy islohotlarga qarshi bo’lgan kishilarga qarshi ta’qib va taziyqlar kuchaydi. Xususan, bolsheviklar mafkurasiga qarshi milliy g’oyalar bilan chiqqan ziyolilar, 1918-1924-yillardagi qarshilik harakati ishtirokchilari hamda ularning qarindosh-urug’lari sovet hokimiyati tomonidan qatag’onga uchradilar. <br>
Qatag’onga uchragan kishilar sharoiti og’ir hududlarga qurilish ishlariga, xususan, “Belomorkanal”, “Belbaltlag”, “Dmitlag” kabi asosan mahbuslar kuchi bilan bunyod etilgan ulkan qurilishlarni qisqa muddatlarda nihoyasiga yetkazish uchun safarbar etildilar. <br>
Muzeyning 6-bo’limi aynan ushbu jarayonlarni yoritib beradi.',
  'exposition-7-text' => '1937-1938-yillarda I.V.Stalin boshchiligida Sovet hokimiyati amalga oshirgan siyosiy qatag’onlar insoniyat tarixidagi eng dahshatli fojialardan biri edi. Bu davrda Sovet hokimiyatiga, uning mafkurasiga qarshi har qanday o’zgacha fikrlash, hatti-harakatga chek qo’yish, xalqni asoratda tutish, partiya va hukumat organlarini so’zsiz itoat etuvchi kadrlar armiyasiga aylantirish maqsadida misli ko’rilmagan ko’lamda qatag’on siyosatini avj oldirdi. <br>
Bu qatag’on to’lqini eng avvalo davlat arboblari, partiya va hukumat organlari, muassasalardagi mas’ul kadrlarga qaratildi. O’zbekistonda bu jarayonda o’sha davrning eng ilg’or, faol, bilimli va tashkilotchi milliy kadrlari, ziyolilari, maorif va madaniyat xodimlari, olimlar, ziyolilar, yozuvchilar mash’um qatag’on qurboni bo’ldilar. Stalin hukumati nafaqat ularning o’zlarini, balki oila a’zolarini ham qatag’on girdobiga tortdi. <br>
Bo’lim ekspozitsiyalarida taniqli davlat arbobi Fayzulla Xo’jayev bilan birga qatag’onga uchragan uning oila a’zolari, bundan tashqari shu yillarda qatag’on etilgan Cho’lpon, Fitrat, Akbar Rustamov, Abdulhay Tojiev singari jamoat aroblarining xotinlari, 1922-yili Germaniyaga o’qishga yuborilgan talabalarning suratlari, shu bilan birga bu davrda qatag’onga uchragan turli soha vakillari – davlat arboblari, adabiyot va san’at namoyandalari, fan va maorif xodimlari, xalq xo’jalikning turli soha vakillarining  suratlari qo’yilgan.',
  'exposition-7-title' => '1937–1938-yillardagi siyosiy qatag’onlar',
  'exposition-8-text' => '1939-1945-yillardagi Ikkinchi jahon urushi insoniyat tarixida eng mash’um fojialardan biri bo’ldi. 1941-yil 22-iyunda gitlerchilar Germaniyasi to’satdan SSSRga hujum qildi. Sovet Ittifoqi tarkibiga kirgan xalqlar qatori o’zbekistonliklar ham fashizmga qarshi urushga jalb etildi. O’zbek xalqi urushning birinchi kunlaridanoq bor kuchini fashizm ustidan g’alabaga safarbar etdi. Urush mamlakat xo’jaligini izdan chiqardi, uning hayotini og’irlashtirib yubordi. Mamlakatda harbiy xolat joriy etildi hamda barcha resurslar mudofaa manfaatlari uchun yo’naltirildi. <br>
Ammo ana shunday og’ir kunlarda ham sovet hokimiyatining qatag’on siyosati to’xtamadi. Sovet hukumati urush arafasi va urush yillarida  yangi bahona, aniqrog’i “fashizmga xayrixohlik kayfiyatiga yo’l qo’ymaslik” bahonasida chegaradosh hududlarda yashovchi xalqlarga qarshi etnik qatag’onlarni boshlab yubordi. Bu jarayonda Yaponiya, Turkiya, Polsha  kabi mamlakatlar bilan chegaradosh hududlarda,  yashovchi koreys, qrimtatarlar, mesxeti turklari, polyaklar, Povolje nemislari va boshqa xalqlar mutlaqo asossiz hamda g’ayriqonuniy ravishda o’z vatanlaridan majburiy ravishda boshqa o’lkalar, xususan O’zbekiston xududiga deportasiya qilindi. Ularni uy-joy, ish, yer va oziq-ovqat bilan ta’minlash o’zbek xalqining zimmasiga tushdi. <br>
Bundan tashqari 40-yillar oxiri va 50-yillar boshida qatag’onlar sovet tuzumi tomonidan O’zbekistonda muntazam o’tkazib kelingan tazyiq va ta’qiblarning navbatdagi bosqichi boshlanganligi va mazkur jarayonida eng avvalo o’z asarlarida o’zbek xalqining o’tmish tarixiga, ma’naviy merosiga  murojaat etib, bu haqda asarlar yozishga jazm etgan olimlar, yozuvchi va shoirlar “o’tmishni ideallashtirishda”, “millatchilikda” ayblanib, qatag’on qilinganligiga oid tarixiy hujjatlar, foto materiallar asosida yoritib berilgan.',
  'exposition-8-title' => '1940–1950-yillardagi siyosiy qatag’onlar.',
  'exposition-9-text' => 'Bu bo’lim ekspozitsiyalarida Sovet hokimiyatining paxta yakkahokimligi siyosatining ayanchli oqibatlari, Orol dengizining qurib qolishi natijasida tabiat muvozanatining buzilishi, ekologik fojianing inson salomatligiga ta’siri diagrammalar yordamida ko’rsatilgan. <br>
XX asrning 80-yillarda sobiq Markaz tomonidan o’zbek xalqiga nisbatan ommaviy qatag’onlarning yangi bosqichi boshlanib, “Paxta ishi” deb nom olgan ushbu siyosiy kampaniya orqali o’zbek xalqi sha’niga turli tuxmat va bo’htonlar yog’dirilib, minglab begunoh kishilar jazoga tortilganligi, “paxta ishi” bo’yicha nohaq ayblangan jabrdiydalarning adolat izlab yozgan arznomalari tergov jarayonidagi azoblar va oilalariga nisbatan uyushtirilgan tazyiqlarga oid materiallar qayd etilgan. Islom Karimov tomonidan  Qashqadaryo viloyatida 1986-yildayoq  “paxta ishi” qurbonlarini oqlash, adolatni tiklash uchun boshlangan sa’yi-harakatlar aks ettirilgan.',
  'exposition-9-title' => '1980-yillardagi qatag’onlar: “Paxta ishi” kampaniyasi',
  'exposition-10-text' => 'Bu bo’lim mustaqillik yillarida O’zbekistonda o’tmishda nohaq qoralangan yoki soxtalashtirilgan tarixiy adolat va milliy qadriyatlarning tiklanishi, istiqlol tufayli berilgan imkoniyatlar yoshlar hayotida qanday imkoniyatlarga yo’l ochib berilganligi tarixiy dalillar asosida ko’rsatiladi. <br>
Ekspozitsiyalarda mustaqillik yillarida tarixiy adolatning qaror topishi tufayli sovet davrida nomlari qoralangan buyuk davlat arboblari, sarkardalar, xususan tarixda chuqur iz qoldirgan Amir Temur, Zahiriddin Muhammad Bobur, Mirzo Ulug’bek, Jaloliddin Manguberdi kabi sarkarda va xukmdorlar haqidagi tarixiy haqiqatning tiklanishi aks ettirilgan. Istiqlol davrida qayta tiklangan va qadr topgan ulkan ma’naviy merosimiz, milliy va diniy qadriyatlarimiz, islom  mutafakkirlari nomlari va ijodiy merosining  tiklanishi, sovet davrida qatag’onga uchragan moddiy yodgorliklarning istiqlol yillarida ta’mirlanishi va obodonlashtirilishi, mustaqillik yillarida yurtimizda islom dini asoslari,  tarixi, islom madaniyati, arxitekturasi  va ma’naviy merosini o’rganish bo’yicha olib borilayotgan samarali ishlar haqidagi tarixiy ma’lumotlar  o’rin olgan. <br>
Bu bo’limda shu bilan birga vatanimiz yoshlariga berilgan cheksiz imkoniyatlar, ularning muvaffaqiyatlari, yoshlarning ilm-fan, sport, ta’lim tizimi, madaniyat va san’ant sohasida erishayotgan  ulkan muvaffaqiyatlari o’z aksini topgan. <br>
Mazkur ilmiy-tematik bo’limlardan qatag’on etilgan vatandoshlarimizning fotosuratlari, shu davrdagi qatag’on siyosatiga oid ko’plab hujjat va materiallar o’rin olgan. Ekspozitsiyalar 30-38-yillar qatag’onining dahshatlarini eslatuvchi avtomobil, GULAG xaritasi, qatag’on qurbonlaridan qolgan shaxsiy buyumlar bilan boyitilgan. <br>
Muzey ekspozitsiyalariga 10 ta sensor kiosklari, 9 monitorlar o’rnatilgan bo’lib, ularga joylangan Mustamlakachilik va qatag’onlar davrining jafolarini aks ettiruvchi noyob arxiv ma’lumotlari, xotiralar, intervyu suhbatlari, musiqiy asarlar, videolavhalar va syujetlardan iborat qayg’uli davr ko’rinishlari, muzeyga tashrif buyuruvchilar uchun xalqimiz tarixida kechgan og’ir daqiqalarni chuqur his qilish imkonini beradi.',
  'exposition-10-title' => 'Mustaqillik yillarida tarixiy adolatning tiklanishi, qatag’on qurbonlari xotirasining abadiylashtirilishi, milliy qadriyatlarni asrab-avaylash va rivojlantirish yo’lida amalga oshirilgan tarixiy ishlar (1991-yildan keyingi davr)',
);
